@url = http://localhost:8080

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Im1hcmNvcyIsImlhdCI6MTUxNjIzOTAyMn0.nMVQAwhRNHJOWx4LCEtAIBZ1dzYAb_9nvZQws0sbRLo

###
GET {{url}}/tarefa
Authorization: Bearer {{token}}

###
GET {{url}}/tarefa/1
Authorization: Bearer {{token}}

###
POST {{url}}/tarefa
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "Tarefa gsotozin",
    "descricao": "Descricao gsotozin",
    "dataInicio": "2024-08-05",
    "dataConclusao": "2024-12-02"
}

###
POST {{url}}/tarefa
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "Tarefa mau",
    "descricao": "Descricao maut",
    "dataInicio": "2024-04-09",
    "dataConclusao": "2024-12-20"
}

###
POST {{url}}/tarefa
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "Tarefa goz",
    "descricao": "Descricao goz",
    "dataInicio": "2024-11-02",
    "dataConclusao": "2024-12-22"
}

###
PUT {{url}}/tarefa/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "Tarefa ganx"
}

###
DELETE {{url}}/tarefa/3
Authorization: Bearer {{token}}

###
POST {{url}}/tarefa/3/2
Authorization: Bearer {{token}}

###
DELETE {{url}}/tarefa/3/2
Authorization: Bearer {{token}}